// <auto-generated />
using System;
using Loto300WebAPI.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loto300WebAPI.Storage.Migrations
{
    [DbContext(typeof(LottoDbContext))]
    partial class LottoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Loto3000App.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberBalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Car",
                            NumberBalls = 7
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vacation",
                            NumberBalls = 6
                        },
                        new
                        {
                            Id = 3,
                            Name = "TV",
                            NumberBalls = 5
                        },
                        new
                        {
                            Id = 4,
                            Name = "100$ Gift Card",
                            NumberBalls = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "50$ Gift Card",
                            NumberBalls = 3
                        });
                });

            modelBuilder.Entity("Loto3000App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Vanja",
                            LastName = "test1",
                            Password = "test1",
                            UserName = "test1",
                            UserType = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dinko",
                            LastName = "test2",
                            Password = "test2",
                            UserName = "test2",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Monika",
                            LastName = "test3",
                            Password = "test3",
                            UserName = "test3",
                            UserType = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jhony",
                            LastName = "Smith",
                            Password = "Jhony123",
                            UserName = "Jhony123",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("Loto300WebApi.Domain.Entites.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumbersDrawn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seesions");
                });

            modelBuilder.Entity("Loto300WebApi.Domain.Entites.TicketNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NubersId")
                        .HasColumnType("int");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserPlayerId");

                    b.ToTable("TicketNumber");
                });

            modelBuilder.Entity("Loto300WebApi.Domain.Entites.TicketNumber", b =>
                {
                    b.HasOne("Loto3000App.Models.User", "UserPlayer")
                        .WithMany()
                        .HasForeignKey("UserPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
